/**
 * Table Type Configurations
 *
 * Complete configurations for all 35 Active Table templates.
 * Based on docs/table-type-templates-reference.md
 *
 * Note: Field labels, option texts, and descriptions use i18n keys.
 * These should be resolved at runtime using Paraglide.
 */

import type { TableConfig } from '../types/table-config-types.js';
import * as TableTypes from '../constants/table-types.js';
import * as FieldTypes from '../constants/field-types.js';

// ============================================
// UUID Generator Helper (for screen IDs)
// ============================================

function generateUUID(): string {
  // Simple UUID v4 generator for kanban/gantt screen IDs
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

// ============================================
// TABLE CONFIGS OBJECT
// ============================================

export const TABLE_CONFIGS: Record<string, TableConfig> = {
  // ============================================
  // 1. BLANK - Bảng trống
  // ============================================
  [TableTypes.TABLE_TYPE_BLANK]: {
    type: TableTypes.TABLE_TYPE_BLANK,
    title: 'tableType_blank_name',
    fields: [],
    actions: [],
    quickFilters: [],
    tableLimit: 1000,
    defaultSort: 'desc',
    e2eeEncryption: false,
    hashedKeywordFields: [],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // 2. JOB_TITLE - Quản lý chức danh
  // ============================================
  [TableTypes.TABLE_TYPE_JOB_TITLE]: {
    type: TableTypes.TABLE_TYPE_JOB_TITLE,
    title: 'tableType_jobTitle_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_jobTitle_name',
        name: 'job_title_name',
        placeholder: 'field_jobTitle_name_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_jobTitle_code',
        name: 'job_title_code',
        placeholder: 'field_jobTitle_code_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        placeholder: 'field_description_placeholder',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          {
            text: 'option_active',
            value: 'active',
            text_color: '#000000',
            background_color: '#d4edda',
          },
          {
            text: 'option_inactive',
            value: 'inactive',
            text_color: '#000000',
            background_color: '#f8d7da',
          },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['job_title_name', 'job_title_code'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_jobTitle_status',
        screenDescription: 'kanban_jobTitle_status_description',
        statusField: 'status',
        kanbanHeadlineField: 'job_title_name',
        displayFields: ['job_title_code', 'status'],
      },
    ],
    ganttCharts: [],
    recordListConfig: {
      layout: 'head-column',
      titleField: 'job_title_name',
      subLineFields: ['job_title_code', 'status'],
    },
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // 3. DEPARTMENT - Quản lý phòng ban
  // ============================================
  [TableTypes.TABLE_TYPE_DEPARTMENT]: {
    type: TableTypes.TABLE_TYPE_DEPARTMENT,
    title: 'tableType_department_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_department_name',
        name: 'department_name',
        placeholder: 'field_department_name_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_department_code',
        name: 'department_code',
        placeholder: 'field_department_code_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        placeholder: 'field_description_placeholder',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_established_date',
        name: 'established_date',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          {
            text: 'option_active',
            value: 'active',
            text_color: '#000000',
            background_color: '#d4edda',
          },
          {
            text: 'option_inactive',
            value: 'inactive',
            text_color: '#000000',
            background_color: '#f8d7da',
          },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['department_name', 'department_code'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_department_status',
        statusField: 'status',
        kanbanHeadlineField: 'department_name',
        displayFields: ['department_code', 'status'],
      },
    ],
    ganttCharts: [],
    recordListConfig: {
      layout: 'head-column',
      titleField: 'department_name',
      subLineFields: ['department_code', 'status'],
    },
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // 4. EMPLOYEE_PROFILE - Quản lý hồ sơ cá nhân
  // ============================================
  [TableTypes.TABLE_TYPE_EMPLOYEE_PROFILE]: {
    type: TableTypes.TABLE_TYPE_EMPLOYEE_PROFILE,
    title: 'tableType_employeeProfile_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_WORKSPACE_USER,
        label: 'field_user',
        name: 'user',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_employee_name',
        name: 'employee_name',
        placeholder: 'field_employee_name_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_employee_code',
        name: 'employee_code',
        placeholder: 'field_employee_code_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_nickname',
        name: 'nickname',
        placeholder: 'field_nickname_placeholder',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_gender',
        name: 'gender',
        required: true,
        options: [
          {
            text: 'option_gender_male',
            value: 'male',
            text_color: '#000000',
            background_color: '#cfe2ff',
          },
          {
            text: 'option_gender_female',
            value: 'female',
            text_color: '#000000',
            background_color: '#f8d7da',
          },
          {
            text: 'option_gender_other',
            value: 'other',
            text_color: '#000000',
            background_color: '#e2e3e5',
          },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_date_of_birth',
        name: 'date_of_birth',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_place_of_birth',
        name: 'place_of_birth',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_native_place',
        name: 'native_place',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_marital_status',
        name: 'marital_status',
        required: false,
        options: [
          {
            text: 'option_marital_single',
            value: 'single',
            text_color: '#000000',
            background_color: '#cfe2ff',
          },
          {
            text: 'option_marital_married',
            value: 'married',
            text_color: '#000000',
            background_color: '#d4edda',
          },
          {
            text: 'option_marital_other',
            value: 'other',
            text_color: '#000000',
            background_color: '#e2e3e5',
          },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_personal_tax_code',
        name: 'personal_tax_code',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_ethnicity',
        name: 'ethnicity',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_religion',
        name: 'religion',
        required: false,
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'gender' }, { fieldName: 'marital_status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['employee_name', 'employee_code', 'nickname'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_employee_gender',
        statusField: 'gender',
        kanbanHeadlineField: 'employee_name',
        displayFields: ['employee_code', 'gender'],
      },
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_employee_marital',
        statusField: 'marital_status',
        kanbanHeadlineField: 'employee_name',
        displayFields: ['employee_code', 'marital_status'],
      },
    ],
    ganttCharts: [],
    recordListConfig: {
      layout: 'head-column',
      titleField: 'employee_name',
      subLineFields: ['employee_code', 'gender'],
    },
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // 5. WORK_PROCESS - Quản lý quá trình công tác
  // ============================================
  [TableTypes.TABLE_TYPE_WORK_PROCESS]: {
    type: TableTypes.TABLE_TYPE_WORK_PROCESS,
    title: 'tableType_workProcess_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_employee_profile',
        name: 'employee_profile',
        required: true,
        referenceTableId: '{EMPLOYEE_PROFILE}',
        referenceLabelField: 'employee_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_process_name',
        name: 'process_name',
        placeholder: 'field_process_name_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_process_code',
        name: 'process_code',
        placeholder: 'field_process_code_placeholder',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_date',
        name: 'start_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_end_date',
        name: 'end_date',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_department',
        name: 'department',
        required: true,
        referenceTableId: '{DEPARTMENT}',
        referenceLabelField: 'department_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_job_title',
        name: 'job_title',
        required: true,
        referenceTableId: '{JOB_TITLE}',
        referenceLabelField: 'job_title_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_salary_setup',
        name: 'salary_setup',
        required: true,
        referenceTableId: '{SALARY_SETUP}',
        referenceLabelField: 'salary_setup_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_salary_grade',
        name: 'salary_grade',
        required: true,
        options: Array.from({ length: 12 }, (_, i) => ({
          text: `option_salary_grade_${i + 1}`,
          value: `salary_grade_${i + 1}`,
          text_color: '#000000',
          background_color: '#e7f1ff',
        })),
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_performance_salary_grade',
        name: 'performance_salary_grade',
        required: true,
        options: Array.from({ length: 12 }, (_, i) => ({
          text: `option_performance_grade_${i + 1}`,
          value: `performance_grade_${i + 1}`,
          text_color: '#000000',
          background_color: '#d4edda',
        })),
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_insurance_salary_grade',
        name: 'insurance_salary_grade',
        required: true,
        options: Array.from({ length: 12 }, (_, i) => ({
          text: `option_insurance_grade_${i + 1}`,
          value: `insurance_grade_${i + 1}`,
          text_color: '#000000',
          background_color: '#fff3cd',
        })),
      },
      {
        type: FieldTypes.FIELD_TYPE_INTEGER,
        label: 'field_dependent_count',
        name: 'dependent_count',
        defaultValue: 0,
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_CHECKBOX_YES_NO,
        label: 'field_is_probation',
        name: 'is_probation',
        defaultValue: false,
        required: false,
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'employee_profile' }, { fieldName: 'department' }, { fieldName: 'job_title' }],
    tableLimit: 30,
    defaultSort: 'desc',
    hashedKeywordFields: ['process_name', 'process_code'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_workProcess_department',
        statusField: 'department',
        kanbanHeadlineField: 'process_name',
        displayFields: ['employee_profile', 'job_title'],
      },
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_workProcess_jobTitle',
        statusField: 'job_title',
        kanbanHeadlineField: 'process_name',
        displayFields: ['employee_profile', 'department'],
      },
    ],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // 6. EMPLOYEE_MONTHLY_METRICS - Chỉ số tháng của nhân sự
  // ============================================
  [TableTypes.TABLE_TYPE_EMPLOYEE_MONTHLY_METRICS]: {
    type: TableTypes.TABLE_TYPE_EMPLOYEE_MONTHLY_METRICS,
    title: 'tableType_employeeMetrics_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_name',
        name: 'name',
        placeholder: 'field_name_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_employee_profile',
        name: 'employee_profile',
        required: true,
        referenceTableId: '{EMPLOYEE_PROFILE}',
        referenceLabelField: 'employee_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_MONTH,
        label: 'field_month',
        name: 'month',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_YEAR,
        label: 'field_year',
        name: 'year',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_official_work_days',
        name: 'official_work_days',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_overtime_work_days',
        name: 'overtime_work_days',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_weekend_overtime_work_days',
        name: 'weekend_overtime_work_days',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_holiday_overtime_work_days',
        name: 'holiday_overtime_work_days',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_performance_percent',
        name: 'performance_percent',
        defaultValue: 100,
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_late_violations',
        name: 'late_violations',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_unexcused_absences',
        name: 'unexcused_absences',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_other_violations',
        name: 'other_violations',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'pending',
        required: true,
        options: [
          {
            text: 'option_pending',
            value: 'pending',
            text_color: '#000000',
            background_color: '#fff3cd',
          },
          {
            text: 'option_finalized',
            value: 'finalized',
            text_color: '#000000',
            background_color: '#d4edda',
          },
          {
            text: 'option_disputed',
            value: 'disputed',
            text_color: '#000000',
            background_color: '#f8d7da',
          },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'employee_profile' }, { fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'desc',
    hashedKeywordFields: ['name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: {
      layout: 'generic-table',
      displayFields: ['employee_profile', 'month', 'year', 'official_work_days', 'status'],
    },
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // 7. PENALTY - Quản lý các khoản phạt
  // ============================================
  [TableTypes.TABLE_TYPE_PENALTY]: {
    type: TableTypes.TABLE_TYPE_PENALTY,
    title: 'tableType_penalty_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_penalty_code',
        name: 'penalty_code',
        placeholder: 'field_penalty_code_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_penalty_name',
        name: 'penalty_name',
        placeholder: 'field_penalty_name_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_penalty_amount',
        name: 'penalty_amount',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_penalty_type',
        name: 'penalty_type',
        required: true,
        options: [
          {
            text: 'option_penalty_fixed',
            value: 'fixed',
            text_color: '#000000',
            background_color: '#cfe2ff',
          },
          {
            text: 'option_penalty_per_violation',
            value: 'per_violation',
            text_color: '#000000',
            background_color: '#fff3cd',
          },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_date',
        name: 'start_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_end_date',
        name: 'end_date',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: false,
        options: [
          {
            text: 'option_active',
            value: 'active',
            text_color: '#000000',
            background_color: '#d4edda',
          },
          {
            text: 'option_inactive',
            value: 'inactive',
            text_color: '#000000',
            background_color: '#f8d7da',
          },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_note',
        name: 'note',
        required: false,
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'penalty_type' }, { fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['penalty_code', 'penalty_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // 8. SALARY_SETUP - Cấu hình bảng lương
  // ============================================
  [TableTypes.TABLE_TYPE_SALARY_SETUP]: {
    type: TableTypes.TABLE_TYPE_SALARY_SETUP,
    title: 'tableType_salarySetup_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_salary_setup_name',
        name: 'salary_setup_name',
        placeholder: 'field_salary_setup_name_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_salary_setup_code',
        name: 'salary_setup_code',
        placeholder: 'field_salary_setup_code_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_salary_policy',
        name: 'salary_policy',
        required: true,
        referenceTableId: '{SALARY_POLICY}',
        referenceLabelField: 'policy_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_official_salary_ratio',
        name: 'official_salary_ratio',
        defaultValue: 1.0,
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_overtime_salary_ratio',
        name: 'overtime_salary_ratio',
        defaultValue: 1.5,
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_weekend_overtime_salary_ratio',
        name: 'weekend_overtime_salary_ratio',
        defaultValue: 2.0,
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_holiday_overtime_salary_ratio',
        name: 'holiday_overtime_salary_ratio',
        defaultValue: 3.0,
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_LIST_RECORD,
        label: 'field_official_benefit_policy',
        name: 'official_benefit_policy',
        required: false,
        referenceTableId: '{BENEFIT_POLICY}',
        referenceLabelField: 'policy_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_LIST_RECORD,
        label: 'field_official_insurance_policy',
        name: 'official_insurance_policy',
        required: false,
        referenceTableId: '{INSURANCE_POLICY}',
        referenceLabelField: 'policy_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_LIST_RECORD,
        label: 'field_official_penalty',
        name: 'official_penalty',
        required: false,
        referenceTableId: '{PENALTY}',
        referenceLabelField: 'penalty_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_probationary_salary_ratio',
        name: 'probationary_salary_ratio',
        defaultValue: 0.7,
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_LIST_RECORD,
        label: 'field_probationary_benefit_policy',
        name: 'probationary_benefit_policy',
        required: false,
        referenceTableId: '{BENEFIT_POLICY}',
        referenceLabelField: 'policy_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_LIST_RECORD,
        label: 'field_probationary_insurance_policy',
        name: 'probationary_insurance_policy',
        required: false,
        referenceTableId: '{INSURANCE_POLICY}',
        referenceLabelField: 'policy_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_LIST_RECORD,
        label: 'field_probationary_penalty',
        name: 'probationary_penalty',
        required: false,
        referenceTableId: '{PENALTY}',
        referenceLabelField: 'penalty_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        required: false,
      },
    ],
    actions: [],
    quickFilters: [],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['salary_setup_name', 'salary_setup_code'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // 9. SALARY_POLICY - Chính sách lương (51 fields!)
  // ============================================
  [TableTypes.TABLE_TYPE_SALARY_POLICY]: {
    type: TableTypes.TABLE_TYPE_SALARY_POLICY,
    title: 'tableType_salaryPolicy_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_policy_name',
        name: 'policy_name',
        placeholder: 'field_policy_name_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_policy_code',
        name: 'policy_code',
        placeholder: 'field_policy_code_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_effective_date',
        name: 'effective_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_expiry_date',
        name: 'expiry_date',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_base_salary',
        name: 'base_salary',
        required: true,
      },
      // 12 Salary Grades
      ...Array.from({ length: 12 }, (_, i) => ({
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: `field_salary_grade_${i + 1}`,
        name: `salary_grade_${i + 1}`,
        required: true,
      })),
      // 12 Performance Salary Grades
      ...Array.from({ length: 12 }, (_, i) => ({
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: `field_performance_salary_grade_${i + 1}`,
        name: `performance_salary_grade_${i + 1}`,
        required: true,
      })),
      // 12 Insurance Salary Grades
      ...Array.from({ length: 12 }, (_, i) => ({
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: `field_insurance_salary_grade_${i + 1}`,
        name: `insurance_salary_grade_${i + 1}`,
        required: true,
      })),
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          {
            text: 'option_active',
            value: 'active',
            text_color: '#000000',
            background_color: '#d4edda',
          },
          {
            text: 'option_inactive',
            value: 'inactive',
            text_color: '#000000',
            background_color: '#f8d7da',
          },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'desc',
    hashedKeywordFields: ['policy_name', 'policy_code'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_salaryPolicy_status',
        statusField: 'status',
        kanbanHeadlineField: 'policy_name',
        displayFields: ['policy_code', 'base_salary', 'effective_date'],
      },
    ],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // 10. TASK_EISENHOWER - Quản lý công việc theo ma trận Eisenhower
  // ============================================
  [TableTypes.TABLE_TYPE_TASK_EISENHOWER]: {
    type: TableTypes.TABLE_TYPE_TASK_EISENHOWER,
    title: 'tableType_taskEisenhower_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SHORT_TEXT,
        label: 'field_task_title',
        name: 'task_title',
        placeholder: 'field_task_title_placeholder',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_task_description',
        name: 'task_description',
        placeholder: 'field_task_description_placeholder',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_date',
        name: 'start_date',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_due_date',
        name: 'duo_date',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_matrix_quadrant',
        name: 'matrix_quadrant',
        required: true,
        options: [
          {
            text: 'option_quadrant_q1',
            value: 'q1_main_stream',
            text_color: '#ffffff',
            background_color: '#dc3545',
          },
          {
            text: 'option_quadrant_q2',
            value: 'q2_growth',
            text_color: '#ffffff',
            background_color: '#28a745',
          },
          {
            text: 'option_quadrant_q3',
            value: 'q3_no_problem',
            text_color: '#ffffff',
            background_color: '#f15c14',
          },
          {
            text: 'option_quadrant_q4',
            value: 'q4_idea',
            text_color: '#ffffff',
            background_color: '#6c757d',
          },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_self_evaluation',
        name: 'self_evaluation',
        required: false,
        options: [
          {
            text: 'option_evaluation_excellent',
            value: 'excellent',
            text_color: '#000000',
            background_color: '#d4edda',
          },
          {
            text: 'option_evaluation_difficult',
            value: 'difficult',
            text_color: '#000000',
            background_color: '#f15c14',
          },
          {
            text: 'option_evaluation_missing_info',
            value: 'missing_info',
            text_color: '#000000',
            background_color: '#fff3cd',
          },
          {
            text: 'option_evaluation_dependency_blocked',
            value: 'dependency_blocked',
            text_color: '#000000',
            background_color: '#cfe2ff',
          },
          {
            text: 'option_evaluation_need_help',
            value: 'need_help',
            text_color: '#ffffff',
            background_color: '#dc3545',
          },
          {
            text: 'option_evaluation_reconsider_plan',
            value: 'reconsider_plan',
            text_color: '#ffffff',
            background_color: '#6f42c1',
          },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_WORKSPACE_USER,
        label: 'field_assignee',
        name: 'assignee',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'pending',
        required: false,
        options: [
          {
            text: 'option_pending',
            value: 'pending',
            text_color: '#000000',
            background_color: '#e2e3e5',
          },
          {
            text: 'option_in_progress',
            value: 'in_progress',
            text_color: '#000000',
            background_color: '#cfe2ff',
          },
          {
            text: 'option_completed',
            value: 'completed',
            text_color: '#000000',
            background_color: '#d4edda',
          },
          {
            text: 'option_cancelled',
            value: 'cancelled',
            text_color: '#000000',
            background_color: '#f8d7da',
          },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }, { fieldName: 'matrix_quadrant' }, { fieldName: 'assignee' }],
    tableLimit: 100,
    defaultSort: 'desc',
    hashedKeywordFields: ['task_title', 'task_description'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_task_matrix',
        statusField: 'matrix_quadrant',
        kanbanHeadlineField: 'task_title',
        displayFields: ['assignee', 'duo_date', 'status'],
      },
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_task_status',
        statusField: 'status',
        kanbanHeadlineField: 'task_title',
        displayFields: ['matrix_quadrant', 'assignee'],
      },
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_task_evaluation',
        statusField: 'self_evaluation',
        kanbanHeadlineField: 'task_title',
        displayFields: ['status', 'assignee'],
      },
    ],
    ganttCharts: [
      {
        ganttScreenId: generateUUID(),
        screenName: 'gantt_task_timeline',
        taskNameField: 'task_title',
        startDateField: 'start_date',
        endDateField: 'duo_date',
      },
    ],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  // ============================================
  // Remaining 25 templates with basic structure
  // (These can be expanded with full field definitions as needed)
  // ============================================

  [TableTypes.TABLE_TYPE_REWARD_POLICY]: {
    type: TableTypes.TABLE_TYPE_REWARD_POLICY,
    title: 'tableType_reward_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_policy_code', name: 'policy_code', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_policy_name', name: 'policy_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_reward_amount',
        name: 'reward_amount',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          { text: 'option_active', value: 'active', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_inactive', value: 'inactive', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['policy_code', 'policy_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_INSURANCE_POLICY]: {
    type: TableTypes.TABLE_TYPE_INSURANCE_POLICY,
    title: 'tableType_insurance_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_policy_code', name: 'policy_code', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_policy_name', name: 'policy_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_employer_contribution_rate',
        name: 'employer_contribution_rate',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_employee_contribution_rate',
        name: 'employee_contribution_rate',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          { text: 'option_active', value: 'active', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_inactive', value: 'inactive', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['policy_code', 'policy_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_LEAVE_POLICY]: {
    type: TableTypes.TABLE_TYPE_LEAVE_POLICY,
    title: 'tableType_leavePolicy_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_leave_code', name: 'leave_code', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_leave_name', name: 'leave_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_INTEGER,
        label: 'field_annual_leave_days',
        name: 'annual_leave_days',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          { text: 'option_active', value: 'active', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_inactive', value: 'inactive', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['leave_code', 'leave_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_APPROVAL_REQUEST]: {
    type: TableTypes.TABLE_TYPE_APPROVAL_REQUEST,
    title: 'tableType_approval_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_title', name: 'title', required: true },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_WORKSPACE_USER,
        label: 'field_requester',
        name: 'requester',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_WORKSPACE_USER,
        label: 'field_approver',
        name: 'approver',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'pending',
        required: true,
        options: [
          { text: 'option_pending', value: 'pending', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_approved', value: 'approved', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_rejected', value: 'rejected', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 50,
    defaultSort: 'desc',
    hashedKeywordFields: ['title'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_approval_status',
        statusField: 'status',
        kanbanHeadlineField: 'title',
        displayFields: ['requester', 'approver'],
      },
    ],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_TIME_OFF_RECORD_MANAGEMENT]: {
    type: TableTypes.TABLE_TYPE_TIME_OFF_RECORD_MANAGEMENT,
    title: 'tableType_timeOff_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_employee_profile',
        name: 'employee_profile',
        required: true,
        referenceTableId: '{EMPLOYEE_PROFILE}',
        referenceLabelField: 'employee_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_date',
        name: 'start_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_end_date',
        name: 'end_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_leave_type',
        name: 'leave_type',
        required: true,
        options: [
          { text: 'option_annual_leave', value: 'annual', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_sick_leave', value: 'sick', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_unpaid_leave', value: 'unpaid', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'pending',
        required: true,
        options: [
          { text: 'option_pending', value: 'pending', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_approved', value: 'approved', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_rejected', value: 'rejected', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }, { fieldName: 'leave_type' }],
    tableLimit: 100,
    defaultSort: 'desc',
    hashedKeywordFields: [],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_timeOff_status',
        statusField: 'status',
        kanbanHeadlineField: 'employee_profile',
        displayFields: ['leave_type', 'start_date', 'end_date'],
      },
    ],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_BENEFIT_PROGRAM_PARTICIPANT]: {
    type: TableTypes.TABLE_TYPE_BENEFIT_PROGRAM_PARTICIPANT,
    title: 'tableType_benefitParticipant_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_employee_profile',
        name: 'employee_profile',
        required: true,
        referenceTableId: '{EMPLOYEE_PROFILE}',
        referenceLabelField: 'employee_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_benefit_program',
        name: 'benefit_program',
        required: true,
        referenceTableId: '{BENEFIT_MANAGEMENT}',
        referenceLabelField: 'benefit_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_enrollment_date',
        name: 'enrollment_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          { text: 'option_active', value: 'active', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_inactive', value: 'inactive', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 100,
    defaultSort: 'desc',
    hashedKeywordFields: [],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_TAX_DEDUCTION]: {
    type: TableTypes.TABLE_TYPE_TAX_DEDUCTION,
    title: 'tableType_taxDeduction_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_deduction_code', name: 'deduction_code', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_deduction_name', name: 'deduction_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_deduction_amount',
        name: 'deduction_amount',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          { text: 'option_active', value: 'active', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_inactive', value: 'inactive', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['deduction_code', 'deduction_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_BENEFIT_POLICY]: {
    type: TableTypes.TABLE_TYPE_BENEFIT_POLICY,
    title: 'tableType_benefitPolicy_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_policy_code', name: 'policy_code', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_policy_name', name: 'policy_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          { text: 'option_active', value: 'active', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_inactive', value: 'inactive', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['policy_code', 'policy_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_BENEFIT_MANAGEMENT]: {
    type: TableTypes.TABLE_TYPE_BENEFIT_MANAGEMENT,
    title: 'tableType_benefitManagement_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_benefit_code', name: 'benefit_code', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_benefit_name', name: 'benefit_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_benefit_policy',
        name: 'benefit_policy',
        required: true,
        referenceTableId: '{BENEFIT_POLICY}',
        referenceLabelField: 'policy_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          { text: 'option_active', value: 'active', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_inactive', value: 'inactive', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 30,
    defaultSort: 'asc',
    hashedKeywordFields: ['benefit_code', 'benefit_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_CULTURE_PROGRAM_REGISTRATION]: {
    type: TableTypes.TABLE_TYPE_CULTURE_PROGRAM_REGISTRATION,
    title: 'tableType_cultureRegistration_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_employee_profile',
        name: 'employee_profile',
        required: true,
        referenceTableId: '{EMPLOYEE_PROFILE}',
        referenceLabelField: 'employee_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_culture_program',
        name: 'culture_program',
        required: true,
        referenceTableId: '{CULTURE_MANAGEMENT}',
        referenceLabelField: 'activity_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_registration_date',
        name: 'registration_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'registered',
        required: true,
        options: [
          { text: 'option_registered', value: 'registered', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_attended', value: 'attended', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_cancelled', value: 'cancelled', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 100,
    defaultSort: 'desc',
    hashedKeywordFields: [],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_CULTURE_MANAGEMENT]: {
    type: TableTypes.TABLE_TYPE_CULTURE_MANAGEMENT,
    title: 'tableType_culture_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_activity_name', name: 'activity_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_activity_description',
        name: 'activity_description',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_activity_type',
        name: 'activity_type',
        required: false,
        options: [
          { text: 'option_team_building', value: 'team_building', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_celebration', value: 'celebration', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_training', value: 'training', text_color: '#000000', background_color: '#fff3cd' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_datetime',
        name: 'start_datetime',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_end_datetime',
        name: 'end_datetime',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'planned',
        required: true,
        options: [
          { text: 'option_planned', value: 'planned', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_ongoing', value: 'ongoing', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_completed', value: 'completed', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 50,
    defaultSort: 'desc',
    hashedKeywordFields: ['activity_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_LEARNING_PROGRESS]: {
    type: TableTypes.TABLE_TYPE_LEARNING_PROGRESS,
    title: 'tableType_learningProgress_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_employee_profile',
        name: 'employee_profile',
        required: true,
        referenceTableId: '{EMPLOYEE_PROFILE}',
        referenceLabelField: 'employee_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_training_program',
        name: 'training_program',
        required: true,
        referenceTableId: '{TRAINING_PROGRAM}',
        referenceLabelField: 'training_name',
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_progress_percentage',
        name: 'progress_percentage',
        defaultValue: 0,
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'not_started',
        required: true,
        options: [
          { text: 'option_not_started', value: 'not_started', text_color: '#000000', background_color: '#e2e3e5' },
          { text: 'option_in_progress', value: 'in_progress', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_completed', value: 'completed', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 100,
    defaultSort: 'desc',
    hashedKeywordFields: [],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_TRAINING_PROGRAM]: {
    type: TableTypes.TABLE_TYPE_TRAINING_PROGRAM,
    title: 'tableType_training_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_training_name', name: 'training_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_training_objectives',
        name: 'training_objectives',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_training_content',
        name: 'training_content',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_training_program_category',
        name: 'training_program_category',
        required: false,
        options: [
          { text: 'option_technical', value: 'technical', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_soft_skills', value: 'soft_skills', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_management', value: 'management', text_color: '#000000', background_color: '#fff3cd' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_date',
        name: 'start_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_end_date',
        name: 'end_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'planned',
        required: true,
        options: [
          { text: 'option_planned', value: 'planned', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_ongoing', value: 'ongoing', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_completed', value: 'completed', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 50,
    defaultSort: 'desc',
    hashedKeywordFields: ['training_name'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_training_status',
        statusField: 'status',
        kanbanHeadlineField: 'training_name',
        displayFields: ['training_program_category', 'start_date', 'end_date'],
      },
    ],
    ganttCharts: [
      {
        ganttScreenId: generateUUID(),
        screenName: 'gantt_training_timeline',
        taskNameField: 'training_name',
        startDateField: 'start_date',
        endDateField: 'end_date',
      },
    ],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_ASSET_MANAGEMENT]: {
    type: TableTypes.TABLE_TYPE_ASSET_MANAGEMENT,
    title: 'tableType_asset_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_asset_name', name: 'asset_name', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_asset_code', name: 'asset_code', required: true },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_asset_type',
        name: 'asset_type',
        required: true,
        options: [
          { text: 'option_equipment', value: 'equipment', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_vehicle', value: 'vehicle', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_property', value: 'property', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'available',
        required: true,
        options: [
          { text: 'option_available', value: 'available', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_in_use', value: 'in_use', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_maintenance', value: 'maintenance', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_retired', value: 'retired', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }, { fieldName: 'asset_type' }],
    tableLimit: 100,
    defaultSort: 'asc',
    hashedKeywordFields: ['asset_name', 'asset_code'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_asset_status',
        statusField: 'status',
        kanbanHeadlineField: 'asset_name',
        displayFields: ['asset_code', 'asset_type'],
      },
    ],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_VENDOR_MANAGEMENT]: {
    type: TableTypes.TABLE_TYPE_VENDOR_MANAGEMENT,
    title: 'tableType_vendor_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_vendor_name', name: 'vendor_name', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_vendor_code', name: 'vendor_code', required: true },
      { type: FieldTypes.FIELD_TYPE_EMAIL, label: 'field_contact_email', name: 'contact_email', required: false },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_contact_phone', name: 'contact_phone', required: false },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_vendor_type',
        name: 'vendor_type',
        required: true,
        options: [
          { text: 'option_supplier', value: 'supplier', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_contractor', value: 'contractor', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_partner', value: 'partner', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'active',
        required: true,
        options: [
          { text: 'option_active', value: 'active', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_inactive', value: 'inactive', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }, { fieldName: 'vendor_type' }],
    tableLimit: 100,
    defaultSort: 'asc',
    hashedKeywordFields: ['vendor_name', 'vendor_code'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_CUSTOMER_PIPELINE]: {
    type: TableTypes.TABLE_TYPE_CUSTOMER_PIPELINE,
    title: 'tableType_customerPipeline_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_customer_name', name: 'customer_name', required: true },
      { type: FieldTypes.FIELD_TYPE_EMAIL, label: 'field_contact_email', name: 'contact_email', required: false },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_contact_phone', name: 'contact_phone', required: false },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_deal_value',
        name: 'deal_value',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_sales_stage',
        name: 'sales_stage',
        required: true,
        options: [
          { text: 'option_lead', value: 'lead', text_color: '#000000', background_color: '#e2e3e5' },
          { text: 'option_qualified', value: 'qualified', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_proposal', value: 'proposal', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_negotiation', value: 'negotiation', text_color: '#000000', background_color: '#ffc107' },
          { text: 'option_closed_won', value: 'closed_won', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_closed_lost', value: 'closed_lost', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_WORKSPACE_USER,
        label: 'field_sales_rep',
        name: 'sales_rep',
        required: false,
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'sales_stage' }, { fieldName: 'sales_rep' }],
    tableLimit: 100,
    defaultSort: 'desc',
    hashedKeywordFields: ['customer_name'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_pipeline_stage',
        statusField: 'sales_stage',
        kanbanHeadlineField: 'customer_name',
        displayFields: ['deal_value', 'sales_rep'],
      },
    ],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_ONBOARDING]: {
    type: TableTypes.TABLE_TYPE_ONBOARDING,
    title: 'tableType_onboarding_name',
    fields: [
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE_RECORD,
        label: 'field_employee_profile',
        name: 'employee_profile',
        required: true,
        referenceTableId: '{EMPLOYEE_PROFILE}',
        referenceLabelField: 'employee_name',
      },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_task_name', name: 'task_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_date',
        name: 'start_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_due_date',
        name: 'due_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'pending',
        required: true,
        options: [
          { text: 'option_pending', value: 'pending', text_color: '#000000', background_color: '#e2e3e5' },
          { text: 'option_in_progress', value: 'in_progress', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_completed', value: 'completed', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 100,
    defaultSort: 'asc',
    hashedKeywordFields: ['task_name'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_onboarding_status',
        statusField: 'status',
        kanbanHeadlineField: 'task_name',
        displayFields: ['employee_profile', 'due_date'],
      },
    ],
    ganttCharts: [
      {
        ganttScreenId: generateUUID(),
        screenName: 'gantt_onboarding_timeline',
        taskNameField: 'task_name',
        startDateField: 'start_date',
        endDateField: 'due_date',
      },
    ],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_HERZBERG_FACTOR]: {
    type: TableTypes.TABLE_TYPE_HERZBERG_FACTOR,
    title: 'tableType_herzberg_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_factor_name', name: 'factor_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_factor_type',
        name: 'factor_type',
        required: true,
        options: [
          { text: 'option_hygiene', value: 'hygiene', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_motivator', value: 'motivator', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        required: false,
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'factor_type' }],
    tableLimit: 50,
    defaultSort: 'asc',
    hashedKeywordFields: ['factor_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_SCAMPER]: {
    type: TableTypes.TABLE_TYPE_SCAMPER,
    title: 'tableType_scamper_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_idea_name', name: 'idea_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_scamper_technique',
        name: 'scamper_technique',
        required: true,
        options: [
          { text: 'option_substitute', value: 'substitute', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_combine', value: 'combine', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_adapt', value: 'adapt', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_modify', value: 'modify', text_color: '#000000', background_color: '#f8d7da' },
          {
            text: 'option_put_to_other_use',
            value: 'put_to_other_use',
            text_color: '#000000',
            background_color: '#e2e3e5',
          },
          { text: 'option_eliminate', value: 'eliminate', text_color: '#000000', background_color: '#ffc107' },
          { text: 'option_reverse', value: 'reverse', text_color: '#ffffff', background_color: '#6f42c1' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        required: false,
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'scamper_technique' }],
    tableLimit: 50,
    defaultSort: 'desc',
    hashedKeywordFields: ['idea_name'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_SWOT_EVALUATION]: {
    type: TableTypes.TABLE_TYPE_SWOT_EVALUATION,
    title: 'tableType_swot_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_item_name', name: 'item_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_swot_category',
        name: 'swot_category',
        required: true,
        options: [
          { text: 'option_strength', value: 'strength', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_weakness', value: 'weakness', text_color: '#000000', background_color: '#f8d7da' },
          { text: 'option_opportunity', value: 'opportunity', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_threat', value: 'threat', text_color: '#000000', background_color: '#fff3cd' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        required: false,
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'swot_category' }],
    tableLimit: 50,
    defaultSort: 'asc',
    hashedKeywordFields: ['item_name'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_swot_category',
        statusField: 'swot_category',
        kanbanHeadlineField: 'item_name',
        displayFields: ['description'],
      },
    ],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_CONTENT_SCRIPT_MANAGEMENT]: {
    type: TableTypes.TABLE_TYPE_CONTENT_SCRIPT_MANAGEMENT,
    title: 'tableType_contentScript_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_title', name: 'title', required: true },
      { type: FieldTypes.FIELD_TYPE_RICH_TEXT, label: 'field_content', name: 'content', required: false },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_content_type',
        name: 'content_type',
        required: true,
        options: [
          { text: 'option_blog', value: 'blog', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_video', value: 'video', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_social', value: 'social', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'draft',
        required: true,
        options: [
          { text: 'option_draft', value: 'draft', text_color: '#000000', background_color: '#e2e3e5' },
          { text: 'option_review', value: 'review', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_published', value: 'published', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }, { fieldName: 'content_type' }],
    tableLimit: 100,
    defaultSort: 'desc',
    hashedKeywordFields: ['title'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_INSIGHT_TTM]: {
    type: TableTypes.TABLE_TYPE_INSIGHT_TTM,
    title: 'tableType_insightTTM_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_insight_name', name: 'insight_name', required: true },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_date',
        name: 'start_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_target_launch_date',
        name: 'target_launch_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'research',
        required: true,
        options: [
          { text: 'option_research', value: 'research', text_color: '#000000', background_color: '#e2e3e5' },
          { text: 'option_development', value: 'development', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_testing', value: 'testing', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_launched', value: 'launched', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 50,
    defaultSort: 'desc',
    hashedKeywordFields: ['insight_name'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_insight_status',
        statusField: 'status',
        kanbanHeadlineField: 'insight_name',
        displayFields: ['start_date', 'target_launch_date'],
      },
    ],
    ganttCharts: [
      {
        ganttScreenId: generateUUID(),
        screenName: 'gantt_insight_timeline',
        taskNameField: 'insight_name',
        startDateField: 'start_date',
        endDateField: 'target_launch_date',
      },
    ],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_PROTOTYPE]: {
    type: TableTypes.TABLE_TYPE_PROTOTYPE,
    title: 'tableType_prototype_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_prototype_name', name: 'prototype_name', required: true },
      { type: FieldTypes.FIELD_TYPE_URL, label: 'field_prototype_url', name: 'prototype_url', required: false },
      {
        type: FieldTypes.FIELD_TYPE_RICH_TEXT,
        label: 'field_description',
        name: 'description',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_date',
        name: 'start_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_completion_date',
        name: 'completion_date',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'planning',
        required: true,
        options: [
          { text: 'option_planning', value: 'planning', text_color: '#000000', background_color: '#e2e3e5' },
          { text: 'option_in_progress', value: 'in_progress', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_testing', value: 'testing', text_color: '#000000', background_color: '#fff3cd' },
          { text: 'option_completed', value: 'completed', text_color: '#000000', background_color: '#d4edda' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }],
    tableLimit: 50,
    defaultSort: 'desc',
    hashedKeywordFields: ['prototype_name'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_prototype_status',
        statusField: 'status',
        kanbanHeadlineField: 'prototype_name',
        displayFields: ['start_date', 'completion_date'],
      },
    ],
    ganttCharts: [
      {
        ganttScreenId: generateUUID(),
        screenName: 'gantt_prototype_timeline',
        taskNameField: 'prototype_name',
        startDateField: 'start_date',
        endDateField: 'completion_date',
      },
    ],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_CONTRACT]: {
    type: TableTypes.TABLE_TYPE_CONTRACT,
    title: 'tableType_contract_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_contract_name', name: 'contract_name', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_contract_code', name: 'contract_code', required: true },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_contract_type',
        name: 'contract_type',
        required: true,
        options: [
          { text: 'option_sales', value: 'sales', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_purchase', value: 'purchase', text_color: '#000000', background_color: '#cfe2ff' },
          { text: 'option_service', value: 'service', text_color: '#000000', background_color: '#fff3cd' },
        ],
      },
      {
        type: FieldTypes.FIELD_TYPE_NUMERIC,
        label: 'field_contract_value',
        name: 'contract_value',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_start_date',
        name: 'start_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_end_date',
        name: 'end_date',
        required: true,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_status',
        name: 'status',
        defaultValue: 'draft',
        required: true,
        options: [
          { text: 'option_draft', value: 'draft', text_color: '#000000', background_color: '#e2e3e5' },
          { text: 'option_active', value: 'active', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_expired', value: 'expired', text_color: '#000000', background_color: '#f8d7da' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'status' }, { fieldName: 'contract_type' }],
    tableLimit: 100,
    defaultSort: 'desc',
    hashedKeywordFields: ['contract_name', 'contract_code'],
    kanbanConfigs: [
      {
        kanbanScreenId: generateUUID(),
        screenName: 'kanban_contract_status',
        statusField: 'status',
        kanbanHeadlineField: 'contract_name',
        displayFields: ['contract_code', 'contract_value'],
      },
    ],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },

  [TableTypes.TABLE_TYPE_HAIR_SALON_CUSTOMER]: {
    type: TableTypes.TABLE_TYPE_HAIR_SALON_CUSTOMER,
    title: 'tableType_hairSalonCustomer_name',
    fields: [
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_customer_name', name: 'customer_name', required: true },
      { type: FieldTypes.FIELD_TYPE_SHORT_TEXT, label: 'field_phone_number', name: 'phone_number', required: false },
      { type: FieldTypes.FIELD_TYPE_EMAIL, label: 'field_email', name: 'email', required: false },
      {
        type: FieldTypes.FIELD_TYPE_DATETIME,
        label: 'field_last_visit_date',
        name: 'last_visit_date',
        required: false,
      },
      {
        type: FieldTypes.FIELD_TYPE_SELECT_ONE,
        label: 'field_customer_tier',
        name: 'customer_tier',
        required: false,
        options: [
          { text: 'option_regular', value: 'regular', text_color: '#000000', background_color: '#e2e3e5' },
          { text: 'option_silver', value: 'silver', text_color: '#000000', background_color: '#d4edda' },
          { text: 'option_gold', value: 'gold', text_color: '#000000', background_color: '#ffc107' },
          { text: 'option_platinum', value: 'platinum', text_color: '#ffffff', background_color: '#6f42c1' },
        ],
      },
    ],
    actions: [],
    quickFilters: [{ fieldName: 'customer_tier' }],
    tableLimit: 100,
    defaultSort: 'desc',
    hashedKeywordFields: ['customer_name', 'phone_number'],
    kanbanConfigs: [],
    ganttCharts: [],
    recordListConfig: null,
    recordDetailConfig: null,
    permissionsConfig: [],
  },
};

// ============================================
// Export default
// ============================================

export default TABLE_CONFIGS;
